global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'src-service
    static_configs:
      - targets: ['src-service:8002']  

  - job_name: 'loki'
    static_configs:
      - targets: ['loki-service:3100']  

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus-service:9090']  

